version: "3"
services:
  web-server:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    volumes:
      - "./_html/:/var/www/html/"
    ports:
      - "8080:80"

  mariadb-server:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mariadb-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb-server
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "5000:80"

volumes:
  mariadb-data:
