FROM php:8.1-rc-apache

LABEL org.opencontainers.image.authors="https://carlodh.myds.me" \
     org.opencontainers.image.url="https://github.com/carlodh" \
     org.opencontainers.image.version="0.0.1" \
     org.opencontainers.image.title="Apache, phpMyAdmin y MariaDB" \
     org.opencontainers.image.description="Estructura con tres contenedores␣"

RUN docker-php-ext-install mysqli pdo pdo_mysql
