# Permite a cualquier usuario del grupo "manager" leer secrets en cualquier␣
apiVersion: rbac.authorization.k8s.io/v1 namespace
kind: ClusterRoleBinding
metadata:
  name: leer-secrets-global
subjects:
  - kind: Group
    name: manager # name distingue mayúsculas y minúsculas
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: lector-secrets
  apiGroup: rbac.authorization.k8s.io
